--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      food-inspection-dimension-model.DM1
--
-- Date Created : Monday, April 21, 2025 00:30:00
-- Target DBMS : Snowflake
--

-- 
-- TABLE: BRIDGE_VIOLATION_INSPECTION 
--
CREATE DATABASE IF NOT EXISTS FOOD_INSPECTION_DB;

USE FOOD_INSPECTION_DB;

CREATE SCHEMA IF NOT EXISTS FOOD_INSPECTION_SCHEMA;

USE SCHEMA FOOD_INSPECTION_SCHEMA;

CREATE TABLE IF NOT EXISTS BRIDGE_VIOLATION_INSPECTION(
    VIOLATION_INSPECTION_SK    NUMBER(10, 0)        NOT NULL,
    VIOLATION_SK               NUMBER(10, 0)        NOT NULL,
    INSPECTION_SK              NUMBER(10, 0)        NOT NULL,
    BUSINESS_SK                NUMBER(10, 0)        NOT NULL,
    LOCATION_SK                NUMBER(10, 0)        NOT NULL,
    INSPECTION_DATE            NUMBER(8, 0)         NOT NULL,
    VIOLATION_COMMENT          VARCHAR(16777216),
    DI_JOB_ID                  VARCHAR(100),
    DI_LOAD_DT                 DATE,
    CONSTRAINT PK_VIOLATION_INSPECTION_SK PRIMARY KEY (VIOLATION_INSPECTION_SK, VIOLATION_SK, INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE) 
)
;



-- 
-- TABLE: DIM_BUSINESS 
--

CREATE TABLE IF NOT EXISTS DIM_BUSINESS(
    BUSINESS_SK       NUMBER(10, 0)    NOT NULL,
    LOCATION_SK       NUMBER(10, 0)    NOT NULL,
    BUSINESS_NAME     VARCHAR(100),
    LICENSE_NUMBER    NUMBER(10, 0),
    FACILITY_TYPE     VARCHAR(100),
    DI_JOB_ID         VARCHAR(100),
    DI_LOAD_DT        DATE,
    CONSTRAINT PK_BUSINESS_SK PRIMARY KEY (BUSINESS_SK, LOCATION_SK) 
)
;



-- 
-- TABLE: DIM_DATE 
--

CREATE TABLE IF NOT EXISTS DIM_DATE(
    DATE_SK        NUMBER(8, 0)    NOT NULL,
    DATE           DATE,
    DAY_ABBR       VARCHAR(5),
    MONTH_ABBR     VARCHAR(5),
    QUARTER_NUM    NUMBER(2, 0),
    YEAR_NUM       NUMBER(4, 0),
    DI_JOB_ID      VARCHAR(100),
    DI_LOAD_DT     DATE,
    CONSTRAINT PK_DATE_SK PRIMARY KEY (DATE_SK) 
)
;



-- 
-- TABLE: DIM_LOCATION 
--

CREATE TABLE IF NOT EXISTS DIM_LOCATION(
    LOCATION_SK       NUMBER(10, 0)    NOT NULL,
    STREET_ADDRESS    VARCHAR(1000),
    CITY              VARCHAR(100),
    STATE             VARCHAR(100),
    ZIPCODE           NUMBER(10, 0),
    DI_JOB_ID         VARCHAR(100),
    DI_LOAD_DT        DATE,
    CONSTRAINT PK_LOCATION_SK PRIMARY KEY (LOCATION_SK) 
)
;



-- 
-- TABLE: DIM_VIOLATION 
--

CREATE TABLE IF NOT EXISTS DIM_VIOLATION(
    VIOLATION_SK             NUMBER(10, 0)     NOT NULL,
    VIOLATION_CODE           NUMBER(10, 0),
    VIOLATION_DESCRIPTION    VARCHAR(16777216),
    SOURCE                   VARCHAR(100),
    DI_JOB_ID                VARCHAR(100),
    DI_LOAD_DT               DATE,
    CONSTRAINT PK_VIOLATION_SK PRIMARY KEY (VIOLATION_SK) 
)
;



-- 
-- TABLE: FCT_INSPECTION 
--

CREATE TABLE IF NOT EXISTS FCT_INSPECTION(
    INSPECTION_SK      NUMBER(10, 0)    NOT NULL,
    BUSINESS_SK        NUMBER(10, 0)    NOT NULL,
    LOCATION_SK        NUMBER(10, 0)    NOT NULL,
    INSPECTION_DATE    NUMBER(8, 0)     NOT NULL,
    INSPECTION_ID      VARCHAR(100),
    INSPECTION_TYPE    VARCHAR(100),
    RISK               VARCHAR(100),
    RESULT             VARCHAR(100),
    DI_JOB_ID          VARCHAR(100),
    DI_LOAD_DT         DATE,
    CONSTRAINT PK_INSPECTION_SK PRIMARY KEY (INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE) 
)
;



-- 
-- TABLE: BRIDGE_VIOLATION_INSPECTION 
--

ALTER TABLE BRIDGE_VIOLATION_INSPECTION ADD CONSTRAINT RefDIM_VIOLATION61 
    FOREIGN KEY (VIOLATION_SK)
    REFERENCES DIM_VIOLATION(VIOLATION_SK)
;

ALTER TABLE BRIDGE_VIOLATION_INSPECTION ADD CONSTRAINT RefFCT_INSPECTION71 
    FOREIGN KEY (INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE)
    REFERENCES FCT_INSPECTION(INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE)
;


-- 
-- TABLE: DIM_BUSINESS 
--

ALTER TABLE DIM_BUSINESS ADD CONSTRAINT RefDIM_LOCATION21 
    FOREIGN KEY (LOCATION_SK)
    REFERENCES DIM_LOCATION(LOCATION_SK)
;


-- 
-- TABLE: FCT_INSPECTION 
--

ALTER TABLE FCT_INSPECTION ADD CONSTRAINT RefDIM_BUSINESS41 
    FOREIGN KEY (BUSINESS_SK, LOCATION_SK)
    REFERENCES DIM_BUSINESS(BUSINESS_SK, LOCATION_SK)
;

ALTER TABLE FCT_INSPECTION ADD CONSTRAINT RefDIM_DATE51 
    FOREIGN KEY (INSPECTION_DATE)
    REFERENCES DIM_DATE(DATE_SK)
;


