CREATE SCHEMA FOOD_INSPECTION_SCHEMA;

CREATE OR REPLACE TABLE DIM_BUSINESS(
    BUSINESS_SK      NUMBER(10, 0)    NOT NULL,
    LOCATION_SK      NUMBER(10, 0)    NOT NULL,
    BUSINESS_NAME    VARCHAR(100),
    FACILITY_TYPE    VARCHAR(100),
    DI_JOB_ID        VARCHAR(100),
    DI_LOAD_DT       DATE,
    CONSTRAINT PK_BUSINESS_SK PRIMARY KEY (BUSINESS_SK, LOCATION_SK) ,
    CONSTRAINT FK_BUSINESS_LOCATION FOREIGN KEY (LOCATION_SK) REFERENCES DIM_LOCATION(LOCATION_SK)
);

CREATE TABLE DIM_DATE(
    DATE_SK        NUMBER(8, 0)    NOT NULL,
    DATE           DATE,
    DAY_ABBR       VARCHAR(5),
    MONTH_ABBR     VARCHAR(5),
    QUARTER_NUM    NUMBER(2, 0),
    YEAR_NUM       NUMBER(4, 0),
    DI_JOB_ID      VARCHAR(100),
    DI_LOAD_DT     DATE,
    CONSTRAINT PK_DATE_SK PRIMARY KEY (DATE_SK) 
);

CREATE TABLE DIM_LOCATION(
    LOCATION_SK       NUMBER(10, 0)    NOT NULL,
    STREET_ADDRESS    VARCHAR(1000),
    CITY              VARCHAR(100),
    STATE             VARCHAR(100),
    ZIPCODE           NUMBER(10, 0),
    DI_JOB_ID         VARCHAR(100),
    DI_LOAD_DT        DATE,
    CONSTRAINT PK_LOCATION_SK PRIMARY KEY (LOCATION_SK) 
);

CREATE TABLE DIM_VIOLATION(
    VIOLATION_SK             NUMBER(10, 0)     NOT NULL,
    VIOLATION_CODE           NUMBER(10, 0),
    VIOLATION_DESCRIPTION    VARCHAR(10000),
    SOURCE                   VARCHAR(100),
    DI_JOB_ID                VARCHAR(100),
    DI_LOAD_DT               DATE,
    CONSTRAINT PK_VIOLATION_SK PRIMARY KEY (VIOLATION_SK) 
);

CREATE OR REPLACE TABLE BRIDGE_VIOLATION_INSPECTION(
    VIOLATION_INSPECTION_SK    NUMBER(10, 0)    NOT NULL,
    VIOLATION_SK               NUMBER(10, 0)    NOT NULL,
    INSPECTION_SK              NUMBER(10, 0)    NOT NULL,
    BUSINESS_SK                NUMBER(10, 0)    NOT NULL,
    LOCATION_SK                NUMBER(10, 0)    NOT NULL,
    INSPECTION_DATE            NUMBER(8, 0)     NOT NULL,
    DI_JOB_ID                  VARCHAR(100),
    DI_LOAD_DT                 DATE,
    CONSTRAINT PK_VIOLATION_INSPECTION_SK PRIMARY KEY (VIOLATION_INSPECTION_SK, VIOLATION_SK, INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE),
    CONSTRAINT FK_BRIDGE_VIOLATION FOREIGN KEY (VIOLATION_SK) REFERENCES DIM_VIOLATION(VIOLATION_SK),
    CONSTRAINT FK_BRIDGE_INSPECTION FOREIGN KEY (INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE) REFERENCES FCT_INSPECTION(INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE)
);

CREATE OR REPLACE TABLE FCT_INSPECTION(
    INSPECTION_SK      NUMBER(10, 0)    NOT NULL,
    BUSINESS_SK        NUMBER(10, 0)    NOT NULL,
    LOCATION_SK        NUMBER(10, 0)    NOT NULL,
    INSPECTION_DATE    NUMBER(8, 0)     NOT NULL,
    INSPECTION_ID      VARCHAR(100),
    INSPECTION_TYPE    VARCHAR(100),
    RISK               VARCHAR(100),
    RESULT             VARCHAR(100),
    DI_JOB_ID          VARCHAR(100),
    DI_LOAD_DT         DATE,
    CONSTRAINT PK_INSPECTION_SK PRIMARY KEY (INSPECTION_SK, BUSINESS_SK, LOCATION_SK, INSPECTION_DATE),
    CONSTRAINT FK_INSPECTION_BUSINESS FOREIGN KEY (BUSINESS_SK, LOCATION_SK) REFERENCES DIM_BUSINESS(BUSINESS_SK, LOCATION_SK),
    CONSTRAINT FK_INSPECTION_DATE FOREIGN KEY (INSPECTION_DATE) REFERENCES DIM_DATE(DATE_SK)
);